"""
deployment_generator.py - Terraform Deployment Folder Generator
================================================================
Generates DEPLOYMENT folders that consume existing modules:
  main.tf        (module call with known values pre-filled)
  terraform.tfvars (variable overrides)
  import_commands.sh  (example import commands - NOT auto-run)
  README.md

SAFETY:
  - Default dry_run=True
  - Never runs terraform commands
  - Never modifies Azure or Terraform state
  - Output goes to /generated for human review
"""

import logging
import re
from pathlib import Path
from typing import Optional, List
from datetime import datetime

from jinja2 import Environment, FileSystemLoader, select_autoescape

from models import (
    DiscoveredResource, GenerationPlan, GeneratedFile,
    GenerationStatus, OutputType, ServiceType
)

logger = logging.getLogger(__name__)

SAFETY_HEADER = """
# ===========================================================================
# AUTO-GENERATED DEPLOYMENT STUB
# Generated by: azure-terraform-module-builder
# Timestamp: {timestamp}
# Source resource: {resource_name}
#
# REVIEW REQUIRED:
#   1. Fill all TODO values
#   2. Run terraform init
#   3. Run terraform plan - review ALL changes
#   4. Run import commands if resource already exists in Azure
#   5. Only then consider terraform apply (with team approval)
#
# NEVER run terraform apply without completing steps 1-4 above.
# ===========================================================================
"""


class DeploymentGenerator:
    """
    Generates Terraform deployment folders that call module scaffolds.

    A deployment folder includes:
    - main.tf           (module call with pre-filled values)
    - terraform.tfvars  (variable values with TODOs)
    - import_commands.sh (example import commands)
    - README.md
    """

    def __init__(
        self,
        output_dir: str,
        module_root: str = "./terraform-modules",
        env_path: str = "edav/dev",
        templates_dir: Optional[str] = None,
        dry_run: bool = True,
    ):
        """
        Args:
            output_dir: Base output directory (./generated).
            module_root: Path to existing terraform-modules repo.
            env_path: Environment path (e.g. edav/dev, corp/prod).
            templates_dir: Optional Jinja2 templates dir.
            dry_run: If True (default), only plans; does not write.
        """
        self.output_dir = Path(output_dir)
        self.module_root = Path(module_root)
        self.env_path = env_path
        self.dry_run = dry_run
        self._timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self._templates_dir = Path(templates_dir) if templates_dir else (
            Path(__file__).parent.parent / "templates"
        )
        self._env: Optional[Environment] = None

    def _get_env(self) -> Environment:
        if self._env is None:
            self._env = Environment(
                loader=FileSystemLoader(str(self._templates_dir)),
                autoescape=select_autoescape([]),
                trim_blocks=True, lstrip_blocks=True,
            )
        return self._env

    def _render(self, template_name: str, **ctx) -> Optional[str]:
        try:
            return self._get_env().get_template(template_name).render(**ctx)
        except Exception:
            return None

    def _safety_header(self, rn: str, is_onboarding: bool = False) -> str:
        if is_onboarding:
            return ONBOARDING_HEADER.format(timestamp=self._timestamp, resource_name=rn)
        return SAFETY_HEADER.format(timestamp=self._timestamp, resource_name=rn)

    def _module_name(self, resource: DiscoveredResource) -> str:
        mapping = {
            ServiceType.AI_SEARCH: "ai_search_service",
            ServiceType.OPENAI: "cognitive_account",
            ServiceType.AI_FOUNDRY: "ai_foundry",
            ServiceType.PRIVATE_ENDPOINT: "private_endpoint",
            ServiceType.DIAGNOSTIC_SETTING: "diagnostic_setting",
            ServiceType.RBAC: "rbac_assignment",
        }
        return mapping.get(resource.service_type, "generic_resource")

    def _module_source(self, module_name: str) -> str:
        """Compute relative path to module from deployment folder."""
        env_depth = len(Path(self.env_path).parts)  # e.g. edav/dev = 2
        # From: generated/deployments/<env_path>/<module_name>/
        # To:   generated/modules/<module_name>/
        ups = "../" * (env_depth + 1)  # up to generated/
        return f"{ups}modules/{module_name}"

    def plan(self, resource: DiscoveredResource) -> GenerationPlan:
        """
        Create a GenerationPlan for deployment files WITHOUT writing.
        """
        plan = GenerationPlan(
            resource=resource,
            service_type=resource.service_type,
            need=resource.need,
            status=GenerationStatus.DRY_RUN_ONLY,
        )

        module_name = self._module_name(resource)
        deploy_path = self.output_dir / "deployments" / self.env_path / module_name
        plan.deployment_output_path = str(deploy_path)
        plan.description = (
            f"Generate deployment '{module_name}/{self.env_path}' "
            f"for '{resource.name}'"
        )

        ctx = self._build_context(resource, module_name)
        plan.planned_files = [
            self._plan_file(deploy_path, "main.tf", OutputType.DEPLOYMENT, ctx),
            self._plan_file(deploy_path, "terraform.tfvars", OutputType.TFVARS, ctx),
            self._plan_file(deploy_path, "import_commands.sh", OutputType.IMPORT_COMMANDS, ctx),
            self._plan_file(deploy_path, "README.md", OutputType.README, ctx),
        ]
        return plan

    def execute(self, plan: GenerationPlan) -> GenerationPlan:
        """Write deployment files. Only called when dry_run=False."""
        if self.dry_run:
            logger.info("[DRY RUN] Would write %d deployment files for %s",
                        plan.file_count, plan.resource.name if plan.resource else "?")
            plan.status = GenerationStatus.DRY_RUN_ONLY
            return plan

        errors = []
        for gf in plan.planned_files:
            try:
                p = Path(gf.full_path)
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(gf.content, encoding="utf-8")
                gf.written = True
                gf.is_dry_run = False
                logger.info("Written: %s", p)
            except OSError as exc:
                gf.error = str(exc)
                errors.append(str(exc))
                logger.error("Failed to write %s: %s", gf.full_path, exc)

        plan.errors = errors
        plan.status = GenerationStatus.ERROR if errors else GenerationStatus.GENERATED
        return plan

    def _plan_file(
        self, base: Path, filename: str, out_type: OutputType, ctx: dict
    ) -> GeneratedFile:
        full_path = base / filename
        rel_path = str(full_path.relative_to(self.output_dir))
        # Try template
        svc = ctx.get("service_type", "generic")
        content = self._render(f"deployment_{svc}_{filename}.j2", **ctx)
        # Fallback
        if content is None:
            content = self._generate_fallback(filename, ctx)
        return GeneratedFile(
            output_type=out_type, relative_path=rel_path,
            full_path=str(full_path), content=content, is_dry_run=self.dry_run,
        )

    def _build_context(self, resource: DiscoveredResource, module_name: str) -> dict:
        first_pe = resource.private_endpoints[0] if resource.private_endpoints else None
        first_diag = resource.diagnostic_settings[0] if resource.diagnostic_settings else None

        # Detect onboarding candidate: resource exists in Azure but no Terraform deployment definition
        # Set by discovery tool classification or inferred from comparison_status field
        comparison_status = getattr(resource, "comparison_status", "")
        is_onboarding_candidate = (
            comparison_status == "terraform_onboarding_candidate"
            or getattr(resource, "is_onboarding_candidate", False)
        )

        return {
            "resource": resource,
            "resource_name": resource.name,
            "resource_type": resource.resource_type,
            "resource_group": resource.resource_group,
            "subscription_id": resource.subscription_id,
            "location": resource.location,
            "sku": resource.sku_name,
            "tags": resource.tags,
            "identity_type": resource.identity.type if resource.identity else "SystemAssigned",
            "public_network_access": resource.public_network_access,
            "first_pe": first_pe,
            "first_diag": first_diag,
            "has_pe": bool(resource.private_endpoints),
            "has_diag": bool(resource.diagnostic_settings),
            "service_type": resource.service_type.value,
            "module_name": module_name,
            "module_source": self._module_source(module_name),
            "env_path": self.env_path,
            "timestamp": self._timestamp,
            # Onboarding candidate flag
            "is_onboarding_candidate": is_onboarding_candidate,
        }

    # -------------------------------------------------------------------------
    # Fallback generators
    # -------------------------------------------------------------------------

    def _generate_fallback(self, filename: str, ctx: dict) -> str:
        dispatch = {
            "main.tf": self._fallback_main,
            "terraform.tfvars": self._fallback_tfvars,
            "import_commands.sh": self._fallback_import,
            "README.md": self._fallback_readme,
        }
        return dispatch.get(filename, lambda c: "# TODO\n")(ctx)

    def _fallback_main(self, ctx: dict) -> str:
        rn = ctx["resource_name"]
        mn = ctx["module_name"]
        src = ctx["module_source"]
        svc = ctx["service_type"]
        pe = ctx.get("first_pe")
        diag = ctx.get("first_diag")
        identity = ctx.get("identity_type", "SystemAssigned")
        public = ctx.get("public_network_access", "")
        public_bool = "false" if (public or "").lower() == "disabled" else "# TODO"
        is_onboarding = ctx.get("is_onboarding_candidate", False)

        # For onboarding candidates, add an explicit comment block
        onboarding_comment = ""
        if is_onboarding:
            onboarding_comment = (
                "# NOTE: TERRAFORM ONBOARDING CANDIDATE\n"
                "# This resource already exists in Azure and was created outside Terraform.\n"
                "# Import existing resources BEFORE applying.\n"
                "# Plan MUST return: Plan: 0 to add, 0 to change, 0 to destroy\n"
            )

        lines = [
            self._safety_header(rn, is_onboarding=is_onboarding),
            onboarding_comment,
            'terraform {',
            '  required_providers {',
            '    azurerm = {',
            '      source  = "hashicorp/azurerm"',
            '      version = "~> 3.0"',
            '    }',
            '  }',
            '  # TODO: Add backend configuration',
            '  # backend "azurerm" {',
            '  #   resource_group_name  = "TODO"',
            '  #   storage_account_name = "TODO"',
            '  #   container_name       = "tfstate"',
            '  #   key                  = "TODO.terraform.tfstate"',
            '  # }',
            '}',
            "",
            'provider "azurerm" {',
            f'  subscription_id = "{ctx.get("subscription_id", "# TODO")}"',
            '  features {}',
            '}',
            "",
            'locals {',
            f'  resource_group_name = "{ctx.get("resource_group", "# TODO")}"',
            f'  location            = "{ctx.get("location", "# TODO")}"',
            '  # TODO: Add environment-specific locals',
            '}',
            "",
            f'module "{mn}" {{',
            f'  source = "{src}"',
            "",
            f'  name                = "{rn}"',
            '  resource_group_name = local.resource_group_name',
            '  location            = local.location',
        ]

        if svc == "ai_search":
            lines += [
                f'  sku                           = "{ctx.get("sku", "standard")}"',
                f'  public_network_access_enabled = {public_bool}',
                f'  identity_type                 = "{identity}"',
                f'  # TODO: replica_count, partition_count',
                f'  log_analytics_workspace_id    = var.log_analytics_workspace_id',
                f'  admin_group_object_id         = var.admin_group_object_id',
                f'  developer_group_object_id     = var.developer_group_object_id',
            ]
        elif svc in ("openai", "ai_foundry"):
            kind = "OpenAI" if svc == "openai" else "AIServices"
            lines += [
                f'  kind                  = "{kind}"',
                f'  sku_name              = "{ctx.get("sku", "S0")}"',
                f'  public_network_access = "Disabled"',
                f'  # custom_subdomain_name = "# TODO"',
                f'  identity_type         = "{identity}"',
                f'  log_analytics_workspace_id = var.log_analytics_workspace_id',
            ]
        elif svc == "private_endpoint":
            lines += [
                f'  subnet_id              = var.subnet_id  # TODO: Detected subnet: {pe.subnet_name if pe else "unknown"}',
                f'  private_link_service_id = "{ctx.get("resource_name", "TODO")}"',  # PE points to parent
                f'  subresource_names      = {json_list(pe.group_ids) if pe and pe.group_ids else "# TODO"}',
                f'  # private_ip_address   = "{pe.private_ip_address if pe else "# TODO"}"',
            ]
        elif svc == "diagnostic_setting":
            lines += [
                f'  target_resource_id         = "TODO: parent resource ID"',
                f'  log_analytics_workspace_id = var.log_analytics_workspace_id  # {diag.log_analytics_workspace_name if diag else "TODO"}',
            ]
        elif svc == "rbac":
            lines += [
                f'  scope                = "TODO: scope"',
                f'  role_definition_name = "TODO: role"',
                f'  principal_id         = var.admin_group_object_id',
            ]

        if svc not in ("private_endpoint", "diagnostic_setting", "rbac"):
            tags = ctx.get("tags", {})
            if tags:
                lines.append('  tags = {')
                for k, v in tags.items():
                    lines.append(f'    {k} = "{v}"')
                lines.append('  }')
            else:
                lines.append('  tags = var.tags  # TODO')

        lines.append('}')
        return "\n".join(lines) + "\n"

    def _fallback_tfvars(self, ctx: dict) -> str:
        rn = ctx["resource_name"]
        svc = ctx["service_type"]
        pe = ctx.get("first_pe")
        diag = ctx.get("first_diag")
        lines = [
            f"# terraform.tfvars - {rn}",
            f"# Generated: {self._timestamp}",
            f"# REVIEW AND FILL ALL TODO VALUES BEFORE USE",
            "",
            f'# TODO: Log Analytics workspace resource ID',
            f'log_analytics_workspace_id = "# TODO"  # Detected: {diag.log_analytics_workspace_id if diag else "not found"}',
            "",
        ]
        if svc in ("ai_search", "openai", "ai_foundry"):
            lines += [
                '# TODO: Azure AD group object IDs',
                'admin_group_object_id     = "# TODO"',
                'developer_group_object_id = "# TODO"',
                "",
            ]
        if svc == "private_endpoint" and pe:
            lines += [
                f'# Private endpoint configuration',
                f'subnet_id = "# TODO: {pe.subnet_id}"',
                f'private_ip_address = "{pe.private_ip_address or "# TODO"}"',
                "",
            ]
        tags = ctx.get("tags", {})
        if tags:
            lines += [
                "# Tags confirmed from Azure",
                "tags = {",
            ]
            for k, v in tags.items():
                lines.append(f'  {k} = "{v}"')
            lines += ["}",""]
        return "\n".join(lines) + "\n"

    def _fallback_import(self, ctx: dict) -> str:
        rn = ctx["resource_name"]
        svc = ctx["service_type"]
        mn = ctx["module_name"]
        is_onboarding = ctx.get("is_onboarding_candidate", False)
        resource_id = f"/subscriptions/{ctx.get('subscription_id','TODO')}/resourceGroups/{ctx.get('resource_group','TODO')}/providers/{ctx.get('resource_type','TODO')}/{rn}"

        # Add onboarding validation note
        onboarding_note = ""
        if is_onboarding:
            onboarding_note = "# ONBOARDING CANDIDATE: All sub-resources must be imported.\n# Plan MUST return: Plan: 0 to add, 0 to change, 0 to destroy before apply.\n#"

        tf_type_map = {
            "ai_search": "azurerm_search_service.this",
            "openai": "azurerm_cognitive_account.this",
            "ai_foundry": "azurerm_cognitive_account.this",
            "private_endpoint": "azurerm_private_endpoint.this",
            "diagnostic_setting": "azurerm_monitor_diagnostic_setting.this",
            "rbac": "azurerm_role_assignment.this",
        }
        tf_addr = tf_type_map.get(svc, "TODO.this")

        return "\n".join([
            "#!/bin/bash",
            "# ===========================================================================",
            "# IMPORT COMMANDS - DO NOT RUN WITHOUT REVIEW",
            f"# Generated: {self._timestamp}",
            f"# Resource: {rn}",
            onboarding_note,
            "# ===========================================================================",
            "#",
            "# BEFORE RUNNING:",
            "#   1. terraform init",
            "#   2. Review all variable values in terraform.tfvars",
            "#   3. Run: terraform plan -var-file=terraform.tfvars",
            "#   4. Only then run the import below",
            "#",
            "# ---------------------------------------------------------------------------",
            "",
            "# Step 1: Initialize Terraform",
            "# terraform init",
            "",
            "# Step 2: (Terraform 1.5+) Preview the import",
            "# terraform plan -generate-config-out=generated_import.tf",
            "",
            f"# Step 3: Import the existing Azure resource",
            f"# terraform import \\",
            f"#   'module.{mn}.{tf_addr}' \\",
            f"#   '{resource_id}'",
            "",
            "# Step 4: Verify state",
            "# terraform show",
            "",
            "# Step 5: Plan to check for drift",
            "# terraform plan -var-file=terraform.tfvars",
            "",
            "# ---------------------------------------------------------------------------",
            "# Private Endpoint Import (if applicable)",
        ] + [
            f"# terraform import 'module.{mn}.azurerm_private_endpoint.this' \\",
            f"#   '/subscriptions/{ctx.get('subscription_id','TODO')}/resourceGroups/{pe.resource_group}/providers/Microsoft.Network/privateEndpoints/{pe.name}'",
        ] if (pe := ctx.get("first_pe")) else [] + [
            "#",
            "# *** NEVER run terraform apply before steps 1-5 above ***",
        ]) + "\n"

    def _fallback_readme(self, ctx: dict) -> str:
        rn = ctx["resource_name"]
        svc = ctx["service_type"].replace("_", " ").title()
        env = ctx.get("env_path", "")
        mn = ctx.get("module_name", "")
        ts = self._timestamp
        return "\n".join([
            f"# Deployment: {svc} - {rn}",
            "",
            f"> Auto-generated deployment folder by azure-terraform-module-builder",
            f"> Environment: `{env}` | Module: `{mn}`",
            f"> Generated: {ts}",
            f"> **Review all TODO values before use.**",
            "",
            "## What This Does",
            "",
            f"Deploys an Azure {svc} resource by calling the `{mn}` module.",
            f"Pre-populated with values discovered from the live Azure environment.",
            "",
            "## Before You Apply",
            "",
            "1. Fill all `# TODO` values in `main.tf` and `terraform.tfvars`",
            "2. Run `terraform init`",
            "3. Run `terraform plan -var-file=terraform.tfvars` and review all changes",
            "4. If resource already exists in Azure, run import commands from `import_commands.sh`",
            "5. Get team approval before `terraform apply`",
            "",
            "## File Overview",
            "",
            "| File | Purpose |",
            "|------|---------|",
            "| `main.tf` | Module call with pre-filled values from Azure discovery |",
            "| `terraform.tfvars` | Variable values (fill TODOs) |",
            "| `import_commands.sh` | Example import commands for existing resources |",
            "",
            "## Safety",
            "",
            "- **Never** run `terraform apply` without completing all pre-apply steps",
            "- Import existing resources before apply to prevent recreation",
            "- All generated files are drafts — human review is required",
        ]) + "\n"


def json_list(items: list) -> str:
    """Format a Python list as a Terraform list literal."""
    if not items:
        return "[]"
    inner = ", ".join(f'"{i}"' for i in items)
    return f"[{inner}]"
