"""
module_generator.py - Terraform Module Scaffold Generator
==========================================================
Generates complete Terraform MODULE folders:
  main.tf, variables.tf, outputs.tf, README.md
for each supported Azure service type.

SAFETY:
  - Default dry_run=True - only plans, never writes
  - Never runs terraform apply/destroy/plan
  - Never modifies Azure
  - All writes go to /generated for human review
"""

import logging
import os
from pathlib import Path
from typing import Optional, List, Dict
from datetime import datetime

from jinja2 import Environment, FileSystemLoader, select_autoescape

from models import (
    DiscoveredResource, GenerationPlan, GeneratedFile,
    GenerationStatus, OutputType, ServiceType, ResourceNeed
)

logger = logging.getLogger(__name__)

SAFETY_HEADER = """
# ===========================================================================
# AUTO-GENERATED by azure-terraform-module-builder
# Generated: {timestamp}
# Source resource: {resource_name}
# REVIEW ALL TODO ITEMS before using in production.
# Never run terraform apply without reviewing terraform plan output.
# ===========================================================================
"""


# ---------------------------------------------------------------------------
# Template environment
# ---------------------------------------------------------------------------

class TemplateEngine:
    """Wrapper around Jinja2 for template rendering with fallbacks."""

    def __init__(self, templates_dir: Optional[str] = None):
        self.templates_dir = Path(templates_dir) if templates_dir else (
            Path(__file__).parent.parent / "templates"
        )
        self._env: Optional[Environment] = None

    def _get_env(self) -> Environment:
        if self._env is None:
            self._env = Environment(
                loader=FileSystemLoader(str(self.templates_dir)),
                autoescape=select_autoescape([]),
                trim_blocks=True,
                lstrip_blocks=True,
                keep_trailing_newline=True,
                undefined=_SilentUndefined,
            )
        return self._env

    def render(self, template_name: str, **context) -> Optional[str]:
        """Render a template, returning None if template not found."""
        try:
            env = self._get_env()
            tmpl = env.get_template(template_name)
            return tmpl.render(**context)
        except Exception as exc:
            logger.debug("Template %s not found or failed: %s", template_name, exc)
            return None


class _SilentUndefined:
    """Silently render undefined Jinja2 variables as empty string."""
    def __init__(self, *args, **kwargs):
        pass
    def __str__(self): return ""
    def __repr__(self): return ""
    def __bool__(self): return False
    def __iter__(self): return iter([])
    def __getattr__(self, name): return self
    def __call__(self, *a, **k): return self


# ---------------------------------------------------------------------------
# Module generator
# ---------------------------------------------------------------------------

class ModuleGenerator:
    """
    Generates Terraform MODULE scaffolds.

    A module scaffold includes:
    - main.tf       (resource definitions)
    - variables.tf  (input variables with descriptions)
    - outputs.tf    (output values)
    - README.md     (module documentation)
    """

    def __init__(
        self,
        output_dir: str,
        templates_dir: Optional[str] = None,
        dry_run: bool = True,
    ):
        """
        Args:
            output_dir: Base output directory (typically ./generated).
            templates_dir: Path to Jinja2 templates.
            dry_run: If True (default), plans but does not write files.
        """
        self.output_dir = Path(output_dir)
        self.dry_run = dry_run
        self.engine = TemplateEngine(templates_dir)
        self._timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def _safety_header(self, resource_name: str) -> str:
        return SAFETY_HEADER.format(
            timestamp=self._timestamp,
            resource_name=resource_name,
        )

    def plan(self, resource: DiscoveredResource) -> GenerationPlan:
        """
        Create a GenerationPlan for a resource WITHOUT writing any files.
        Always safe to call.

        Args:
            resource: Discovered Azure resource.

        Returns:
            GenerationPlan with planned files listed.
        """
        plan = GenerationPlan(
            resource=resource,
            service_type=resource.service_type,
            need=resource.need,
            status=GenerationStatus.DRY_RUN_ONLY,
        )

        # Determine module path
        module_name = self._module_name(resource)
        module_path = self.output_dir / "modules" / module_name
        plan.module_output_path = str(module_path)
        plan.description = (
            f"Generate module scaffold '{module_name}' "
            f"for {resource.resource_type} '{resource.name}'"
        )

        # Plan files
        ctx = self._build_context(resource)
        plan.planned_files = [
            self._plan_file(module_path, "main.tf", OutputType.MODULE, ctx),
            self._plan_file(module_path, "variables.tf", OutputType.VARIABLES, ctx),
            self._plan_file(module_path, "outputs.tf", OutputType.OUTPUTS, ctx),
            self._plan_file(module_path, "README.md", OutputType.README, ctx),
        ]
        return plan

    def execute(self, plan: GenerationPlan) -> GenerationPlan:
        """
        Execute a GenerationPlan: write files to disk.
        Only called when dry_run=False.

        Args:
            plan: Previously created GenerationPlan.

        Returns:
            Updated plan with written status.
        """
        if self.dry_run:
            logger.info("[DRY RUN] Would generate %d files for %s",
                        plan.file_count, plan.resource.name if plan.resource else "?")
            plan.status = GenerationStatus.DRY_RUN_ONLY
            return plan

        errors = []
        for gf in plan.planned_files:
            try:
                path = Path(gf.full_path)
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(gf.content, encoding="utf-8")
                gf.written = True
                gf.is_dry_run = False
                logger.info("Written: %s", path)
            except OSError as exc:
                gf.error = str(exc)
                errors.append(f"{gf.relative_path}: {exc}")
                logger.error("Failed to write %s: %s", gf.full_path, exc)

        plan.errors = errors
        plan.status = (
            GenerationStatus.ERROR if errors
            else GenerationStatus.GENERATED
        )
        return plan

    def _module_name(self, resource: DiscoveredResource) -> str:
        """Derive a module folder name from the resource."""
        mapping = {
            ServiceType.AI_SEARCH: "ai_search_service",
            ServiceType.OPENAI: "cognitive_account",
            ServiceType.AI_FOUNDRY: "ai_foundry",
            ServiceType.PRIVATE_ENDPOINT: "private_endpoint",
            ServiceType.DIAGNOSTIC_SETTING: "diagnostic_setting",
            ServiceType.RBAC: "rbac_assignment",
        }
        return mapping.get(resource.service_type, "generic_resource")

    def _plan_file(
        self,
        module_path: Path,
        filename: str,
        output_type: OutputType,
        context: dict,
    ) -> GeneratedFile:
        """Create a planned GeneratedFile with rendered content."""
        full_path = module_path / filename
        rel_path = str(full_path.relative_to(self.output_dir))

        # Try template first
        svc = context.get("service_type", "generic")
        template_name = f"module_{svc}_{filename}.j2"
        content = self.engine.render(template_name, **context)

        # Fall back to generic generator
        if content is None:
            content = self._generate_fallback(filename, context)

        return GeneratedFile(
            output_type=output_type,
            relative_path=rel_path,
            full_path=str(full_path),
            content=content,
            is_dry_run=self.dry_run,
        )

    def _build_context(self, resource: DiscoveredResource) -> dict:
        """Build the Jinja2 template context from a resource."""
        first_pe = resource.private_endpoints[0] if resource.private_endpoints else None
        first_diag = resource.diagnostic_settings[0] if resource.diagnostic_settings else None
        return {
            "resource": resource,
            "resource_name": resource.name,
            "resource_type": resource.resource_type,
            "resource_group": resource.resource_group,
            "location": resource.location,
            "sku": resource.sku_name,
            "tags": resource.tags,
            "identity_type": resource.identity.type if resource.identity else "SystemAssigned",
            "public_network_access": resource.public_network_access,
            "first_pe": first_pe,
            "first_diag": first_diag,
            "has_pe": bool(resource.private_endpoints),
            "has_diag": bool(resource.diagnostic_settings),
            "service_type": resource.service_type.value,
            "timestamp": self._timestamp,
        }

    # ---------------------------------------------------------------------------
    # Fallback content generators
    # ---------------------------------------------------------------------------

    def _generate_fallback(self, filename: str, ctx: dict) -> str:
        """Generate content without templates."""
        svc = ctx.get("service_type", "generic")
        dispatch = {
            "main.tf": self._fallback_main,
            "variables.tf": self._fallback_variables,
            "outputs.tf": self._fallback_outputs,
            "README.md": self._fallback_readme,
        }
        fn = dispatch.get(filename, self._fallback_generic)
        return fn(svc, ctx)

    def _fallback_main(self, svc: str, ctx: dict) -> str:
        rn = ctx.get("resource_name", "TODO")
        rg = ctx.get("resource_group", "")
        loc = ctx.get("location", "")
        sku = ctx.get("sku", "")
        pe = ctx.get("first_pe")
        identity = ctx.get("identity_type", "SystemAssigned")
        public_access = ctx.get("public_network_access", "")
        public_bool = "false" if (public_access or "").lower() == "disabled" else "# TODO: true or false"

        tf_type_map = {
            "ai_search": "azurerm_search_service",
            "openai": "azurerm_cognitive_account",
            "ai_foundry": "azurerm_cognitive_account",
            "private_endpoint": "azurerm_private_endpoint",
            "diagnostic_setting": "azurerm_monitor_diagnostic_setting",
            "rbac": "azurerm_role_assignment",
        }
        tf_type = tf_type_map.get(svc, "# TODO: azurerm_resource_type")

        lines = [
            self._safety_header(rn),
            f'resource "{tf_type}" "this" {{',
            f'  name                = var.name',
            f'  resource_group_name = var.resource_group_name',
            f'  location            = var.location',
        ]

        if svc == "ai_search":
            lines += [
                f'  sku = var.sku',
                f'  public_network_access_enabled = {public_bool}',
                f'  # TODO: replica_count, partition_count, hosting_mode',
                f'  identity {{',
                f'    type = var.identity_type',
                f'  }}',
            ]
        elif svc in ("openai", "ai_foundry"):
            lines += [
                f'  kind                  = var.kind',
                f'  sku_name              = var.sku_name',
                f'  public_network_access = var.public_network_access',
                f'  custom_subdomain_name = var.custom_subdomain_name',
                f'  identity {{',
                f'    type = var.identity_type',
                f'  }}',
            ]
        elif svc == "private_endpoint":
            lines += [
                f'  subnet_id = var.subnet_id',
                f'  private_service_connection {{',
                f'    name                           = "${{var.name}}-connection"',
                f'    private_connection_resource_id = var.private_link_service_id',
                f'    is_manual_connection           = false',
                f'    subresource_names              = var.subresource_names',
                f'  }}',
                f'  # TODO: private_dns_zone_group if DNS integration required',
            ]
        elif svc == "diagnostic_setting":
            lines += [
                f'  target_resource_id         = var.target_resource_id',
                f'  log_analytics_workspace_id = var.log_analytics_workspace_id',
                f'  # TODO: log and metric blocks',
            ]
        elif svc == "rbac":
            lines += [
                f'  scope                = var.scope',
                f'  role_definition_name = var.role_definition_name',
                f'  principal_id         = var.principal_id',
            ]

        if svc not in ("private_endpoint", "diagnostic_setting", "rbac"):
            lines.append(f'  tags = var.tags')

        lines.append(f'}}')  
        return "\n".join(lines) + "\n"

    def _fallback_variables(self, svc: str, ctx: dict) -> str:
        rn = ctx.get("resource_name", "TODO")
        pe = ctx.get("first_pe")
        diag = ctx.get("first_diag")
        tags = ctx.get("tags", {})

        common_vars = [
            ("name", "string", f'"{rn}"', f"The name of the {svc} resource"),
            ("resource_group_name", "string", None, "Resource group name"),
            ("location", "string", f'"{ctx.get("location", "")}"',"Azure location"),
        ]
        svc_vars: list = []

        if svc == "ai_search":
            svc_vars = [
                ("sku", "string", f'"{ctx.get("sku", "standard")}"', "Search service SKU"),
                ("identity_type", "string", '"' + ctx.get("identity_type","SystemAssigned") + '"', "Managed identity type"),
                ("public_network_access_enabled", "bool", "false", "Enable public network access"),
                ("replica_count", "number", "1", "TODO: Number of replicas"),
                ("partition_count", "number", "1", "TODO: Number of partitions"),
            ]
        elif svc in ("openai", "ai_foundry"):
            kind = "OpenAI" if svc == "openai" else "AIServices"
            svc_vars = [
                ("kind", "string", f'"{kind}"', "Cognitive services kind"),
                ("sku_name", "string", f'"{ctx.get("sku", "S0")}"', "SKU name"),
                ("public_network_access", "string", '"Disabled"', "Public network access setting"),
                ("custom_subdomain_name", "string", "null", "TODO: Custom subdomain"),
                ("identity_type", "string", '"SystemAssigned"', "Managed identity type"),
            ]
        elif svc == "private_endpoint":
            svc_vars = [
                ("subnet_id", "string", None, f"TODO: Subnet ID - detected: {pe.subnet_id if pe else 'unknown'}"),
                ("private_link_service_id", "string", None, "Parent resource ID to connect to"),
                ("subresource_names", "list(string)", '[]', "TODO: Subresource names (e.g. searchService)"),
                ("private_ip_address", "string", "null", f"TODO: Static private IP - detected: {pe.private_ip_address if pe else 'unknown'}"),
            ]
            common_vars = common_vars[:2]  # No location needed for PE
        elif svc == "diagnostic_setting":
            svc_vars = [
                ("target_resource_id", "string", None, "ID of the resource to attach diagnostics to"),
                ("log_analytics_workspace_id", "string", None, f"TODO: Log Analytics workspace ID - detected: {diag.log_analytics_workspace_id if diag else 'unknown'}"),
                ("log_categories", "list(string)", '[]', "Log categories to enable"),
                ("metric_categories", "list(string)", '["AllMetrics"]', "Metric categories to enable"),
            ]
            common_vars = common_vars[:1]  # Only name
        elif svc == "rbac":
            svc_vars = [
                ("scope", "string", None, "Scope for the role assignment"),
                ("role_definition_name", "string", None, "TODO: Role definition name (e.g. Contributor)"),
                ("principal_id", "string", None, "TODO: Object ID of principal"),
                ("principal_type", "string", '"ServicePrincipal"', "Type of principal"),
            ]
            common_vars = []

        all_vars = common_vars + svc_vars
        # Add tags
        if svc not in ("diagnostic_setting", "rbac"):
            tags_default = "{}"
            if tags:
                inner = ", ".join(f'"{k}" = "{v}"' for k, v in tags.items())
                tags_default = "{ " + inner + " }"
            all_vars.append(("tags", "map(string)", tags_default, "Resource tags"))

        lines = [self._safety_header(rn)]
        for var_name, var_type, default, desc in all_vars:
            lines.append(f'variable "{var_name}" {{')
            lines.append(f'  description = "{desc}"')
            lines.append(f'  type        = {var_type}')
            if default is not None:
                lines.append(f'  default     = {default}')
            lines.append('}')
            lines.append("")
        return "\n".join(lines) + "\n"

    def _fallback_outputs(self, svc: str, ctx: dict) -> str:
        rn = ctx.get("resource_name", "TODO")
        lines = [
            self._safety_header(rn),
            'output "id" {',
            '  description = "Resource ID"',
            '  value       = RESOURCE_REF.this.id',
            '  # TODO: Replace RESOURCE_REF with correct resource type',
            '}',
            "",
            'output "name" {',
            '  description = "Resource name"',
            '  value       = RESOURCE_REF.this.name',
            '}',
        ]
        if svc == "ai_search":
            lines += [
                "",
                'output "primary_key" {',
                '  description = "Primary admin key - handle with care"',
                '  value       = azurerm_search_service.this.primary_key',
                '  sensitive   = true',
                '}',
            ]
        elif svc in ("openai", "ai_foundry"):
            lines += [
                "",
                'output "endpoint" {',
                '  description = "Service endpoint URL"',
                '  value       = azurerm_cognitive_account.this.endpoint',
                '}',
                "",
                'output "primary_access_key" {',
                '  description = "Primary access key - handle with care"',
                '  value       = azurerm_cognitive_account.this.primary_access_key',
                '  sensitive   = true',
                '}',
            ]
        elif svc == "private_endpoint":
            lines += [
                "",
                'output "private_ip_address" {',
                '  description = "Private IP address of the endpoint"',
                '  value       = azurerm_private_endpoint.this.private_service_connection[0].private_ip_address',
                '}',
            ]
        return "\n".join(lines) + "\n"

    def _fallback_readme(self, svc: str, ctx: dict) -> str:
        rn = ctx.get("resource_name", "TODO")
        rtype = ctx.get("resource_type", "")
        ts = self._timestamp
        svc_display = svc.replace("_", " ").title()
        lines = [
            f"# Terraform Module: {svc_display}",
            f"",
            f"> Auto-generated by azure-terraform-module-builder on {ts}",
            f"> Source resource: `{rn}` ({rtype})",
            f"> **Review all TODO items before use in production.**",
            f"",
            f"## Purpose",
            f"",
            f"Terraform module for managing an Azure {svc_display} resource.",
            f"",
            f"## Usage",
            f"",
            f"```hcl",
            f'module "{svc}" {{',
            f'  source = "path/to/this/module"',
            f"",
            f'  name                = "{rn}"',
            f'  resource_group_name = "# TODO: resource group"',
            f'  location            = "{ctx.get("location", "# TODO")}"',
            f"",
            f'  # TODO: Review and fill all required variables',
            f"}}",
            f"```",
            f"",
            f"## Important Notes",
            f"",
            f"- **NEVER** run `terraform apply` without reviewing `terraform plan` output first",
            f"- If the resource already exists in Azure, run import commands before apply",
            f"- Review the `import_commands.sh` file in the deployment folder for import examples",
            f"",
            f"## Variables",
            f"",
            f"See `variables.tf` for full variable documentation.",
            f"",
            f"## Outputs",
            f"",
            f"See `outputs.tf` for available output values.",
        ]
        return "\n".join(lines) + "\n"

    def _fallback_generic(self, svc: str, ctx: dict) -> str:
        return f"# TODO: {svc} - generated by azure-terraform-module-builder\n"
